version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sciuser
      POSTGRES_PASSWORD: sci_password
      POSTGRES_DB: scientia_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sciuser -d scientia_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
