version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: scientia_db_docker
    environment:
      POSTGRES_USER: sciuser
      POSTGRES_PASSWORD: sci_password
      POSTGRES_DB: scientia_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sciuser -d scientia_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres-net

volumes:
  postgres_data:

networks:
  postgres-net:
    driver: bridge
